apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
      - name: file-service
        image: file-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_URI
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FILE_DB_NAME
        - name: FILE_STORAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FILE_STORAGE_PATH
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        volumeMounts:
        - name: file-storage
          mountPath: /shared/files
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: default
spec:
  selector:
    app: file-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP 