apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskbox-app
  labels:
    app: taskbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskbox
  template:
    metadata:
      labels:
        app: taskbox
    spec:
      containers:
      - name: taskbox
        image: localhost:5000/taskbox_test:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: taskbox-service
spec:
  selector:
    app: taskbox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
